// <auto-generated />
using System;
using Escola.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Escola.Migrations
{
    [DbContext(typeof(EscolaDataContext))]
    partial class EscolaDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Escola.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("DATETIME")
                        .HasColumnName("DataExclusao");

                    b.Property<DateTime>("DataInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("DataInclusao")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DataMatricula")
                        .HasColumnType("DATETIME")
                        .HasColumnName("DataMatricula");

                    b.Property<DateTime?>("DataRecisao")
                        .HasColumnType("DATETIME")
                        .HasColumnName("DataRecisao");

                    b.Property<DateTime?>("DataUltAtu")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("DataUltAtu")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("PessoaId")
                        .HasMaxLength(10)
                        .HasColumnType("INT")
                        .HasColumnName("PessoaId");

                    b.Property<string>("Ra")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("Ra");

                    b.Property<int?>("UsuExclusaoId")
                        .HasColumnType("INT")
                        .HasColumnName("UsuExclusaoId");

                    b.Property<int>("UsuInclusaoId")
                        .HasColumnType("INT")
                        .HasColumnName("UsuInclusaoId");

                    b.Property<int?>("UsuUltAtuId")
                        .IsRequired()
                        .HasColumnType("INT")
                        .HasColumnName("UsuUltAtuId");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Ra" }, "IDX_Alunos_Ra")
                        .IsUnique();

                    b.ToTable("Alunos", (string)null);
                });

            modelBuilder.Entity("Escola.Models.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("VARCHAR(8)")
                        .HasColumnName("Cep");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("Complemento");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("DATETIME")
                        .HasColumnName("DataExclusao");

                    b.Property<DateTime>("DataInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("DataInclusao")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DataUltAtu")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("DataUltAtu")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("VARCHAR(80)")
                        .HasColumnName("Logradouro");

                    b.Property<int>("Numero")
                        .HasColumnType("INT")
                        .HasColumnName("Numero");

                    b.Property<int>("PessoaId")
                        .HasMaxLength(10)
                        .HasColumnType("INT")
                        .HasColumnName("PessoaId");

                    b.Property<int?>("UsuExclusaoId")
                        .HasColumnType("INT")
                        .HasColumnName("UsuExclusaoId");

                    b.Property<int>("UsuInclusaoId")
                        .HasColumnType("INT")
                        .HasColumnName("UsuInclusaoId");

                    b.Property<int?>("UsuUltAtuId")
                        .IsRequired()
                        .HasColumnType("INT")
                        .HasColumnName("UsuUltAtuId");

                    b.HasKey("Id");

                    b.ToTable("Enderecos", (string)null);
                });

            modelBuilder.Entity("Escola.Models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("VARCHAR(11)")
                        .HasColumnName("Cpf");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("DATETIME")
                        .HasColumnName("DataExclusao");

                    b.Property<DateTime>("DataInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("DataInclusao")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("DATETIME")
                        .HasColumnName("DataNascimento");

                    b.Property<DateTime?>("DataUltAtu")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("DataUltAtu")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("VARCHAR(80)")
                        .HasColumnName("Email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("VARCHAR(80)")
                        .HasColumnName("Nome");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("VARCHAR(11)")
                        .HasColumnName("Telefone");

                    b.Property<int?>("UsuExclusaoId")
                        .HasColumnType("INT")
                        .HasColumnName("UsuExclusaoId");

                    b.Property<int>("UsuInclusaoId")
                        .HasColumnType("INT")
                        .HasColumnName("UsuInclusaoId");

                    b.Property<int?>("UsuUltAtuId")
                        .IsRequired()
                        .HasColumnType("INT")
                        .HasColumnName("UsuUltAtuId");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Cpf" }, "IDX_Pessoas_Cpf")
                        .IsUnique();

                    b.ToTable("Pessoas", (string)null);
                });

            modelBuilder.Entity("Escola.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("VARCHAR(80)")
                        .HasColumnName("Tipo");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Escola.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("DATETIME")
                        .HasColumnName("DataExclusao");

                    b.Property<DateTime>("DataInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("DataInclusao")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DataUltAtu")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("DataUltAtu")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("VARCHAR(80)")
                        .HasColumnName("Email");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("VARCHAR(80)")
                        .HasColumnName("Nome");

                    b.Property<int?>("RoleId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("RoleId")
                        .HasDefaultValueSql("1");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("VARCHAR(16)")
                        .HasColumnName("Senha");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Escola.Models.Usuario", b =>
                {
                    b.HasOne("Escola.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Usuarios_Roles_Id");

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
